repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        language: golang
        types: ["file", "non-executable", "text", "yaml"]
        files: ^.github/workflows